version: "3"
services:
  node:
    image: "gcr.io/google-appengine/nodejs"
    volumes:
      - ./:/app
    depends_on:
      - memorystore
      - cloudsql
    ports:
      - "8080:8080"
    networks:
      - redis
      - postgres

  memorystore:
    image: redis:3.2.11
    networks:
      - redis

  cloudsql:
    image: postgres:9.6
    volumes:
      - ./postgres.conf:/etc/postgresql/postgresql.conf:ro
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=M75YE6XscWpG3AHt
    networks:
      - postgres


networks:
  redis:
  postgres:
